name: Vaults
main: Vaults\MainClass
version: 1.0.0
api: [2.0.0]
author: NetworkGG team
description: Put ur custom enchants and favorite gear in personal vaults!
commands:
   pv:
      description: Main command
permissions:
     Vaults.*:
      default: op
      description: Allows them to access all pv commandas
      
